import 'package:flutter/material.dart';

TextEditingController fname = TextEditingController();
TextEditingController lname = TextEditingController();
TextEditingController dobMonth = TextEditingController();
TextEditingController dobDay = TextEditingController();
TextEditingController dobYear = TextEditingController();
TextEditingController phonenumber = TextEditingController();
TextEditingController country = TextEditingController();
TextEditingController address = TextEditingController();
TextEditingController province = TextEditingController();
TextEditingController city = TextEditingController();
TextEditingController postalcode = TextEditingController();
TextEditingController rent = TextEditingController();
TextEditingController water = TextEditingController();
TextEditingController electricity = TextEditingController();
TextEditingController other = TextEditingController();
TextEditingController totalPlannedBudget = TextEditingController();
TextEditingController personalSavings = TextEditingController();
TextEditingController totalExpenditures = TextEditingController();
TextEditingController netBalance = TextEditingController();
TextEditingController cardHolderName = TextEditingController();
TextEditingController cardNumber = TextEditingController();
TextEditingController cardMonth = TextEditingController();
TextEditingController cardYear = TextEditingController();
TextEditingController securityCode = TextEditingController();
TextEditingController cardVerificationCode = TextEditingController();
TextEditingController emailaddress = TextEditingController();
TextEditingController password = TextEditingController();
TextEditingController confirmpassword = TextEditingController();
TextEditingController paymentTitle = TextEditingController();
TextEditingController payment = TextEditingController();
TextEditingController paymentMonth = TextEditingController();
TextEditingController paymentDay = TextEditingController();
TextEditingController paymentYear = TextEditingController();
TextEditingController pickedDay = TextEditingController();

